services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: margo_mitro_old
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT:-9001}:80"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1024M"
